version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ../setup.sh:/docker-entrypoint-initdb.d/setup.sh:ro
      - ../install.sql:/install.sql:ro
      - ../structure.sql:/structure.sql:ro
      - ../data.sql:/data.sql:ro